rsvplist.settings:
  type: config_object
  lable: RSVP list Content Type Settings
  mapping:
    allowed_types:
      type: sequence
      label: Content types the RSVP form can display on
      sequence:
        type: string
        label: Content type
