<?php
/**
 * @file
 * This file demonstrates how to use hook function.
 */

 /**
  * Implement hook_cron
  *
  */
 function mymodule_cron() {
  \Drupal::messenger()->addMessage(t("Hellow there from my side now"));

 }
/**
 * Implements hook_form_alter
 */
 function mymodule_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //\Drupal::messenger()->addMessage(t("form_id of this form is @id: ",['@id' => $form_id]));
  if ($form_id == 'node_article_edit_form') {
    $form['actions']['submit']['#value'] = t("Save this awesome article");
  }
 }


